### PR TITLE
add planet list to output table

### PR DESCRIPTION
**Pull request by douglase**
It would be helpful to have the status of the planet included in the output table, this pull request adds an additional column with that information. Please let me know if there are any conventions I missed. Thank you.

### CODE REVIEW

**Comment by hannorein** [comment]
I agree. Some planets are members of multiple lists. Is this PR going to print out the list you're interested in?

**Comment by douglase** [comment]
I hadn't noticed that, this PR is just getting the first parameter returned by __getParameter(planet,"list")__, 
It looks like the way to get a list of all the lists a planet is on would be to use treeobject.findall()  instead of findtext()? I will give that a try.

**Comment by hannorein** [comment]
Yes, it should probably be some sort of "findall". For the table, one option would be to output just a 0/1 flag that tells whether a planet is in the confirmed list or not (but not bother with all the other lists).

**Comment by douglase** [comment]
the latest commit adds all of the lists a planet is on, adding escape double quotes around a comma separated list if there are multiple items.

**Pull request merged**
